require(tidyverse)
require(readr)

ACT_Clean <- read.csv('Data/ACT_School_Scores_2019.csv') %>%
  filter(Valid.Tests >= 10) %>%
  mutate(District.Name = as.character(District.Name),
         School.Name = as.character(School.Name),
         Subgroup = as.character(Subgroup),
         Participation.Rate = as.numeric(as.character(Participation.Rate)),
         Average.English.Score = as.numeric(as.character(Average.English.Score)),
         Average.Math.Score = as.numeric(as.character(Average.Math.Score)),
         Average.Reading.Score = as.numeric(as.character(Average.Reading.Score)),
         Average.Science.Score = as.numeric(as.character(Average.Math.Score)),
         Average.Composite.Score = as.numeric(as.character(Average.Composite.Score)),
         Number.Scoring.21.or.Higher = as.numeric(as.character(Number.Scoring.21.or.Higher)),
         Number.Scoring.Below.19 = as.numeric(as.character(Number.Scoring.Below.19))) %>% 
  select(-Percent.Scoring.21.or.Higher, -Percent.Scoring.Below.19)



MNPD_Incidents_Clean <- read.csv('Data/MNPD_Incidents_2019.csv') %>%
  mutate(Primary.Key = as.character(Primary.Key),
         Report.Type.Description = case_when(Report.Type == 'D' ~ 'DISPATCHED',
                                             Report.Type == 'O' ~ 'OTHER',
                                             Report.Type == 'S' ~ 'SELF-INITIATED',
                                             Report.Type == 'T' ~ 'TELESERVE',
                                             Report.Type == 'W' ~ 'WALK-IN',
                                             T ~ as.character(Report.Type.Description)),
         Incident.Status.Description = as.character(Incident.Status.Description),
         Investigation.Status = as.character(Investigation.Status),
         Incident.Occurred = as.character(Incident.Occurred),
         Incident.Reported = as.character(Incident.Reported),
         Incident.Location = as.character(Incident.Location),
         Location.Description = as.character(Location.Description),
         Offense.NIBRS = as.character(Offense.NIBRS),
         Offense.Description = case_when(Offense.NIBRS == '09A' ~ 'Murder and Non-negligent Manslaughter',
                                         Offense.NIBRS == '09B' ~ 'Negligent Manslaughter',
                                         Offense.NIBRS == '09C' ~ 'Justifiable Homicide',
                                         Offense.NIBRS == '100' ~ 'Kidnaping/Abduction',
                                         Offense.NIBRS == '11A' ~ 'Forcible Rape',
                                         Offense.NIBRS == '11B' ~ 'Forcible Sodomy',
                                         Offense.NIBRS == '11C' ~ 'Sexual Assault with an Object',
                                         Offense.NIBRS == '11D' ~ 'Forcible Fondling',
                                         Offense.NIBRS == '120' ~ 'Robbery',
                                         Offense.NIBRS == '13A' ~ 'Aggravated Assault',
                                         Offense.NIBRS == '13B' ~ 'Simple Assault',
                                         Offense.NIBRS == '13C' ~ 'Intimidation',
                                         Offense.NIBRS == '13D' ~ 'Stalking',
                                         Offense.NIBRS == '200' ~ 'Arson',
                                         Offense.NIBRS == '210' ~ 'Extortion/Blackmail',
                                         Offense.NIBRS == '220' ~ 'Burglary/Breaking & Entering',
                                         Offense.NIBRS == '23A' ~ 'Pocket-picking',
                                         Offense.NIBRS == '23B' ~ 'Purse-snatching',
                                         Offense.NIBRS == '23C' ~ 'Shoplifting',
                                         Offense.NIBRS == '23D' ~ 'Theft From Building',
                                         Offense.NIBRS == '23E' ~ 'From Coin-Operated Machine or Device',
                                         Offense.NIBRS == '23F' ~ 'Theft From Motor Vehicle',
                                         Offense.NIBRS == '23G' ~ 'Theft of Motor Vehicle Parts or Accessories',
                                         Offense.NIBRS == '23H' ~ 'All Other Larceny',
                                         Offense.NIBRS == '240' ~ 'Motor Vehicle Theft',
                                         Offense.NIBRS == '250' ~ 'Counterfeiting/Forgery',
                                         Offense.NIBRS == '26A' ~ 'False/Pretenses/Swindle/Confidence Game',
                                         Offense.NIBRS == '26B' ~ 'Credit Card/Automatic Teller Machine Fraud',
                                         Offense.NIBRS == '26C' ~ 'Impersonation',
                                         Offense.NIBRS == '26D' ~ 'Welfare Fraud',
                                         Offense.NIBRS == '26E' ~ 'Wire Fraud',
                                         Offense.NIBRS == '26F' ~ 'Identity Theft',
                                         Offense.NIBRS == '26G' ~ 'Hacking/Computer Invasion',
                                         Offense.NIBRS == '270' ~ 'Embezzlement',
                                         Offense.NIBRS == '280' ~ 'Stolen Property Offenses (Receiving, etc.)',
                                         Offense.NIBRS == '290' ~ 'Destruction/Damage/Vandalism of Property', 
                                         Offense.NIBRS == '35A' ~ 'Drug/Narcotic Violations',
                                         Offense.NIBRS == '35B' ~ 'Drug Equipment Violations',
                                         Offense.NIBRS == '36A' ~ 'Incest',
                                         Offense.NIBRS == '36B' ~ 'Statutory Rape',
                                         Offense.NIBRS == '370' ~ 'Pornography/Obscene Material',
                                         Offense.NIBRS == '39A' ~ 'Betting/Wagering',
                                         Offense.NIBRS == '39B' ~ 'Operating/Promoting/Assisting Gambling',
                                         Offense.NIBRS == '39C' ~ 'Gambling Equipment Violations',
                                         Offense.NIBRS == '39D' ~ 'Sports Tampering',
                                         Offense.NIBRS == '40A' ~ 'Prostitution',
                                         Offense.NIBRS == '40B' ~ 'Assisting or Promoting Prostitution',
                                         Offense.NIBRS == '40C' ~ 'Purchasing Prostitution',
                                         Offense.NIBRS == '510' ~ 'Bribery',
                                         Offense.NIBRS == '520' ~ 'Weapon Law Violations',
                                         Offense.NIBRS == '610' ~ 'Abortion',
                                         Offense.NIBRS == '620' ~ 'Accidental Injury',
                                         Offense.NIBRS == '630' ~ 'Aircraft Accident',
                                         Offense.NIBRS == '640' ~ 'Non-Reportable Homicide',
                                         Offense.NIBRS == '64A' ~ 'Human Trafficking, Commercial Sex Acts',
                                         Offense.NIBRS == '64B' ~ 'Human Trafficking, Involuntary Servitude',
                                         Offense.NIBRS == '650' ~ 'Bombing',
                                         Offense.NIBRS == '660' ~ 'Civil Rights',
                                         Offense.NIBRS == '680' ~ 'Death - Accidental',
                                         Offense.NIBRS == '685' ~ 'Death - Natural',
                                         Offense.NIBRS == '690' ~ 'Death - Suicide',
                                         Offense.NIBRS == '695' ~ 'Death - Other',
                                         Offense.NIBRS == '700' ~ 'Escape',
                                         Offense.NIBRS == '710' ~ 'Violation of Order of Protection',
                                         Offense.NIBRS == '715' ~ 'Found/Lost Property',
                                         Offense.NIBRS == '720' ~ 'Harassment',
                                         Offense.NIBRS == '730' ~ 'Indecent Exposure',
                                         Offense.NIBRS == '735' ~ 'Legal Intervention',
                                         Offense.NIBRS == '740' ~ 'Matter of Record',
                                         Offense.NIBRS == '750' ~ 'Obscene Conduct',
                                         Offense.NIBRS == '760' ~ 'Overdose - Accidental',
                                         Offense.NIBRS == '770' ~ 'Psychological Evaluation',
                                         Offense.NIBRS == '780' ~ 'Recovered Property',
                                         Offense.NIBRS == '790' ~ 'Riots - Inciting',
                                         Offense.NIBRS == '800' ~ 'Watercraft Accident',
                                         Offense.NIBRS == '810' ~ 'Lost Property',
                                         Offense.NIBRS == '820' ~ 'Suspicious Object',
                                         Offense.NIBRS == '850' ~ 'Violation of Order of Protection',
                                         Offense.NIBRS == '90A' ~ 'Bad Checks',
                                         Offense.NIBRS == '90B' ~ 'Curfew/Loitering/Vagrancy/Violations',
                                         Offense.NIBRS == '90C' ~ 'Disorderly Conduct',
                                         Offense.NIBRS == '90D' ~ 'Driving Under The Influence',
                                         Offense.NIBRS == '90E' ~ 'Drunkenness',
                                         Offense.NIBRS == '90F' ~ 'Family Offenses, Nonviolent',
                                         Offense.NIBRS == '90G' ~ 'Liquor Law Violations',
                                         Offense.NIBRS == '90H' ~ 'Peeping Tom',
                                         Offense.NIBRS == '90I' ~ 'Runaway',
                                         Offense.NIBRS == '90J' ~ 'Trespass of Real Property',
                                         Offense.NIBRS == '90Z' ~ 'All Other Offenses',
                                         T ~ ''),
         Weapon.Primary = as.character(Weapon.Primary),
         Weapon.Description = case_when(Weapon.Primary == '01' ~ 'Handgun',
                                        Weapon.Primary == '01A' ~ 'Handgun Automatic',
                                        Weapon.Primary == '01S' ~ 'Handgun Semi-Automatic',
                                        Weapon.Primary == '02' ~ 'Rifle',
                                        Weapon.Primary == '02A' ~ 'Rifle Automatic',
                                        Weapon.Primary == '02S' ~ 'Rifle Semi-Automatic',
                                        Weapon.Primary == '03' ~ 'Shotgun',
                                        Weapon.Primary == '04' ~ 'Revolver',
                                        Weapon.Primary == '05' ~ 'Other Firearm',
                                        Weapon.Primary == '06' ~ 'Knife/Cutting Instrument',
                                        Weapon.Primary == '07' ~ 'Blunt Object',
                                        Weapon.Primary == '08' ~ 'Motor Vehicle',
                                        Weapon.Primary == '09' ~ 'Personal (Hands, Etc.)',
                                        Weapon.Primary == '10' ~ 'Poison',
                                        Weapon.Primary == '11' ~ 'Explosives',
                                        Weapon.Primary == '12' ~ 'Fire/Incendiary Devices',
                                        Weapon.Primary == '13' ~ 'Drugs/Narcotics/Sleeping Pills',
                                        Weapon.Primary == '14' ~ 'Asphyxiation',
                                        Weapon.Primary == '15' ~ 'Other',
                                        Weapon.Primary == '16' ~ 'Unknown',
                                        Weapon.Primary == '17' ~ 'None',
                                        Weapon.Primary == '18' ~ 'Bondage',
                                        T ~ 'Unknown'),
         Domestic.Related = as.character(Domestic.Related),
         Victim.Type = as.character(Victim.Type),
         Victim.Description = case_when(Victim.Type == 'B' ~ 'Business',
                                        Victim.Type == 'F' ~ 'Financial Institution',
                                        Victim.Type == 'G' ~ 'Government',
                                        Victim.Type == 'I' ~ 'Individual (18 and Over)',
                                        Victim.Type == 'O' ~ 'Other',
                                        Victim.Type == 'P' ~ 'Police Officer',
                                        Victim.Type == 'R' ~ 'Religious',
                                        Victim.Type == 'S' ~ 'Society',
                                        Victim.Type == 'U' ~ 'Unknown',
                                        T ~ 'Unknown'),
         Victim.Description = as.character(Victim.Description),
         Victim.Gender = as.character(Victim.Gender),
         Victim.Gender = if_else(Victim.Gender == 'W', 'F', Victim.Gender),
         Victim.Race = case_when(Victim.Ethnicity == 'Hispanic' ~ 'Hispanic',
                                 Victim.Race == 'A' ~ 'Asian',
                                 Victim.Race == 'B' ~ 'Black',
                                 Victim.Race == 'H' ~ 'Hispanic',
                                 Victim.Race == 'O' ~ 'Other',
                                 Victim.Race == 'I' ~ 'Native American',
                                 Victim.Race == 'P' ~ 'Pacific Islander',
                                 Victim.Race == 'U' ~ 'Unknown',
                                 Victim.Race == 'W' ~ 'White',
                                 T ~ ''),
         Victim.County.Resident = if_else(grepl('Resident', Victim.County.Resident),
                                          as.character(Victim.County.Resident),
                                          'UNKNOWN')) %>%
  #formatting for Incident Occurred Time
  separate(Incident.Occurred, into = c('Occ.Date', 'Occ.Time', 'Occ.Noon'), sep = ' ') %>%
  separate(Occ.Time, into = c('Occ.Hour', 'Occ.Minute', 'Occ.Second'), sep = ':') %>%
  mutate(Occ.Hour = as.numeric(Occ.Hour),
         Occ.Hour = if_else(Occ.Noon == 'AM', Occ.Hour, Occ.Hour + 12),
         Occ.Time = paste(Occ.Hour, Occ.Minute, Occ.Second, sep = ':'),
         Incident.Occurred = as.POSIXct(paste(Occ.Date, Occ.Time), format = '%m/%d/%Y %H:%M:%S')) %>%
  #formatting for Incident Reported Time
  separate(Incident.Reported, into = c('Rep.Date', 'Rep.Time', 'Rep.Noon'), sep = ' ') %>%
  separate(Rep.Time, into = c('Rep.Hour', 'Rep.Minute', 'Rep.Second'), sep = ':') %>%
  mutate(Rep.Hour = as.numeric(Rep.Hour),
         Rep.Hour = if_else(Rep.Noon == 'AM', Rep.Hour, Rep.Hour + 12),
         Rep.Time = paste(Rep.Hour, Rep.Minute, Rep.Second, sep = ':'),
         Incident.Reported = as.POSIXct(paste(Rep.Date, Rep.Time), format = '%m/%d/%Y %H:%M:%S')) %>%
  #removing unnecessary columns
  select(-Report.Type, -Incident.Status.Code, -Location.Code, -Offense.NIBRS, -Weapon.Primary, -Victim.Type, -Victim.Ethnicity, -Mapped.Location) %>%
  #reformatting columns
  select(Primary.Key:Investigation.Status, Incident.Occurred, Incident.Reported, Incident.Location:Longitude)



